
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mac?zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: cxd950101
    password: cxd950101
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    #\u63A7\u5236\u53F0\u663E\u793ASQL
    show-sql: false
    properties:
     hibernate:
      format_sql: true

server:
  port: 8182
  